### PR TITLE
README.md : Specify that commands must be launched in the Visual Studio Code's Command Palette.

### PR DESCRIPTION
**Pull request by xan2622**
Specify that commands must be launched in the Visual Studio Code's Command Palette.

### CODE REVIEW

**Comment by Mateusz-Grzelinski** [comment]
do we have any command that can or should be executed  NOT in command palete?

**Comment by xan2622** [comment]
I've been thinking this information might be useful for people unfamiliar with Visual Studio Code and with Blender scripting.
Just to help them quickly find where to type these commands.

**Comment by xan2622** [comment]
If you think there are too many unnecessary "_in VS Code's Command Palette_"s in this patch, could I request that only the changes on [line 36](https://github.com/JacquesLucke/blender_vscode/pull/216/commits/588e7c710b408ebbcffde9ed9bf90a56e2407900#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R36) be kept?

One indication at the beginning of the document would probably be enough, the other sentences (lines 60, 109, 130, 138) might not need to be changed, indeed.

**Comment by Mateusz-Grzelinski** [comment]
ok, i will accept. I will not stress to much about readme.

**Pull request merged**
