### PR TITLE
fix #1 Append a setting justMyCode to the list of Addon settings

### PR DESCRIPTION
**Pull request by satabol**
fix #1 Append a setting justMyCode to the list of Addon settings

image

Result:

image

### CODE REVIEW

**Comment by satabol** [comment]
Hi @JacquesLucke . I'm one of developers of [Sverchok Addon](https://github.com/nortikin/sverchok) and I'm using your addon two years. I like it. Sverchok use many external libraries and it is convenient to allow developers like me to debug into external libraries. I saw a PR to add parameter **justMyCode** into the code of your plugin but I have a proposal to add a setting into your plugin to allow developers to select enable or disable debug external python library. Can you review it?

**Review by JacquesLucke — COMMENTED** [review]
Why is it necessary to pass the data through Blender instead of just keeping it on the vscode side? Seems like just reading the config variable in `SERVER_handleRequest` instead of getting it from Blender should work just as well and avoids some boilerplate.

**Comment by satabol** [comment]
@JacquesLucke - you are right! Is it good now?

**Review by JacquesLucke — CHANGES_REQUESTED** [review]
Almost.
* [ ] Add entry in changelog file.
* [ ] Follow code style (missing space in `justMyCode:boolean`).

**Review by JacquesLucke — APPROVED** [review]

**Pull request merged**
