### PR TITLE
Support for command to run on macOS

### PR DESCRIPTION
**Pull request by BennyKok**
tested on macOS 10.14
btw do you have any roadmap  on this, I can help out on adding some features, looks interesting to me ha ha.

btw, how do you get the auto complete working in vs code?

### CODE REVIEW

**Comment by JacquesLucke** [comment]
Will this fail when there are spaces in the filepaths?
As I said, I hope to be able to get rid of this platform dependent code and use features that vs code provides, that will make it easier :)

I do not have a roadmap yet. I to work some on it to get the basic structure right. But then I'd be happy to get some more help! (in a few weeks I guess, I'm working on this in my freetime and not as part of my job in the Blender Institute).

The normal autocompletion should already work when you just install the python extension. I made a simple test for autocompleting blenders apis but so far I only got it to work in quite simple cases. So I will postpone the autocompletion stuff a bit. It is an isolates feature anyway and does not need to work to get the basic structure of the extension right.

**Comment by BennyKok** [comment]
Oh I see, it is not working if I added space in the path... Hum, but usually people just copy the full set of path, so I guess it won't be a problem. 

I am not that familiar with what vs code have already, well it must be a lot better if there is function to directly start a program with args, with checking for which platform is that.

The auto complete I mean is for the blender apis, ha ha, cuz I originally wanted to try do some blender scripting, so I got hooked up by your vids.

btw, I not a extension dev, I am just a programmer that use vs code for Unity and general scripting, so I don't quite familiar with extension development in vs code, but I kinda get the hang of it by looking at the code.

**Comment by BennyKok** [comment]
Just now I have also tried the `spawn` function, it is not working, seems only the exec function works

**Comment by JacquesLucke** [comment]
I got rid of this os dependency, so this patch is not needed anymore. Thanks anyway!

**Pull request closed without merging**
